# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2184e55e584c91661f26e1bcfe246cac0c4ba1cb35cc7c8aa5cd80fb727f611f9c4c68634dfe883acbbba6eac22f6c04e49bf24d042b6181a67b337241af688

test:
  secret_key_base: 3d221fb085b99ac4065c74ce9b7b9647485eed1b97947e762a0a764bc10be24f201a8077b8de97f4c3e840dda2ed3b6e6d53c0e2ceb3e13d11ddbec83d6a251e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
